### ISSUE TITLE
Access Token expires after one hour. So unable to execute big scripts more than an hour.

### ISSUE THREAD

**Issue by sabariramesh** [MicrosoftDocs/partner-center-docs-powershell#120]
Hi,
   I have connected to exchange online powershell using access token. It expires after an hour. So, big scripts are not able to complete. Scripts ended with **Access is denied** It stopped in mid way. Is there any to bypass and able to run script continously.

**Comment by isaiahwilliams** [comment]
@sabariramesh if you are using the Partner Center PowerShell module, then you can authenticate using a refresh token instead of an access token. Using this approach the module will handle the refresh of the token for you. This will allow you to perform long running operations and avoid the error. See [Connect-PartnerCenter](https://docs.microsoft.com/powershell/module/partnercenter/connect-partnercenter) example 3 for more information.

**Comment by JasonWHowell** [comment]
@sabariramesh it appears a solution has been provided by Isaiah. Please let us know if this hasn't resolved your issue. I'll resolve the issue for now. Thanks, Jason #please-close
