### ISSUE TITLE
Cannot get Azure PowerShell example to work

### ISSUE THREAD

**Issue by RichardKForester** [MicrosoftDocs/partner-center-docs-powershell#39]
Hello.  I am not able to get this example to work.  First, there seems to be a couple bugs.

First: Connect-AzAccount -AccessToken $token.AccessToken -GraphAccessToken $graphToken.AccessToken -TenantId '&lt;TenantId&gt;'.   Shouldn't $token.AccessToken instead be $azureToken.AccessToken?

Second: PowerShell is prompting for TenantId when the New-PartnerAccessToken lines are run.

Also, not sure about this line: $refreshToken = 'Your-Refresh-Token-Value'

What exactly is the my refresh token value?  Is this the value that Microsoft Authenticator refreshes every 30 seconds?  Presuming it is and I make the appropriate changes to the code from the example it still fails:

New-PartnerAccessToken : AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: 01916f19-4d43-4119-a924-d5a171240e00
Correlation ID: aaa4d82c-1eb8-48ca-8ebe-70278cad291f
Timestamp: 2019-06-26 12:43:47Z

Can you please help me with this?  I'm trying to get Connect-AzAccount working again after enabling MFA.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cdc6d30-fa74-f007-682c-e9c91598adb0
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Multi-factor Authentication](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-1.5)
* Content Source: [docs-conceptual/partnercenterps-1.5/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by gesbeckj** [comment]
Take a look at https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

There are some steps you need to perform to create an Azure Application, register it and get the refresh token. See the section "Performing the Consent"

**Comment by isaiahwilliams** [comment]
@RichardKForester are you still encountering issues with this?

**Comment by mwasham** [comment]
There is no -Consent paramater on the current version New-PartnerAccessToken 
$token = New-PartnerAccessToken -Consent 
I see a cmdlet for New-PartnerCustomerApplicationConsent but it isn't clear what/why/how to use it.

**Comment by isaiahwilliams** [comment]
@mwasham that parameter was removed with the release of the 2.0 version of the module. Instead of using that parameter you will use something similar to the following 

```powershell
$credential = Get-Credential
New-PartnerAccessToken -ApplicationId 'xxxx-xxxx-xxxx-xxxx' -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation' -ServicePrincipal -Credential $credential -Tenant 'xxxx-xxxx-xxxx-xxxx' -UseAuthorizationCode
```

See [breaking changes](https://docs.microsoft.com/en-us/powershell/partnercenter/breaking-changes?view=partnercenterps-2.0) for more information on the changes.

**Comment by jonwbstr** [comment]
Thought I posted this yesterday... When trying the new method I get the following error. 

What does this error mean?
New-PartnerAccessToken : AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should bepresented.

```
$c = get-credential
$c|Add-Member NoteProperty ApplicationID ('xxxx-xxxx-xxxx-xxxx')
$c|Add-Member NoteProperty PartnerTenantId ('xxxx-xxxx-xxxx-xxxx')

PS C:\Users\ptazadmin> New-PartnerAccessToken -ApplicationId $c.ApplicationID -Scopes 'https://api.partnercenter.microso
ft.com/user_impersonation' -ServicePrincipal -Credential $c -Tenant $c.PartnerTenantId -UseAuthorizationCode
WARNING: Attempting to launch a browser for authorization code login.
WARNING: We have launched a browser for you to login. For the old experience with device code flow, please run
'New-PartnerAccessToken -UseDeviceAuthentication'.
New-PartnerAccessToken : AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be
presented.
Trace ID: 74a09907-5a42-4be2-a1da-8be082780e00
Correlation ID: 2dbc56db-5e63-46f4-aaf1-0642fef990f1
Timestamp: 2019-10-28 22:03:01Z
At line:1 char:1
+ New-PartnerAccessToken -ApplicationId $c.ApplicationID -Scopes 'https ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-PartnerAccessToken], MsalServiceException
    + FullyQualifiedErrorId : Microsoft.Identity.Client.MsalServiceException,Microsoft.Store.PartnerCenter.PowerShell.
   Commands.NewPartnerAccessToken
```

**Comment by isaiahwilliams** [comment]
@jonwbstr based on what you have shared this error is due to the fact you are using a native application instead of web application. When using a native application you will use the following 

```powershell
New-PartnerAccessToken -ApplicationId $c.ApplicationID -Scopes 'https://api.partnercenter.microso
ft.com/user_impersonation' -Tenant $c.PartnerTenantId -UseAuthorizationCode
```

The `ServicePrincipal` parameter is only used if the Azure Active Directory application that you are using is a web application. Native applications do not have this, and when that parameter is specified it will take the password from the credentials and use that are the client_secret value when requesting a new access token.

**Comment by jonwbstr** [comment]
I tried creating a new application using the instructions for partnercenter-1.5 and when performing consent I receive the error saying "AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application"

I tried making it a public application, and received the same error.

**Comment by jonwbstr** [comment]
When comparing the older working app, I noticed the reply url is using the platform "mobile and desktop application" Tried to reconfigure the url and also noticed that the "Web application" platform doesn't like the uri "urn:ietf:wg:oauth:2.0:oob" because web applications must start with http or https (according to the interface). Alas, even as a mobile and desktop application, I still get the same reply url is wrong error.

I also switch the new application to public and back again in my attempts to generate consent without success. The old app will let me get tokens using an interactive login, and I can't do a non-interactive refresh of the tokens.

The new app won't let me get tokens.

**Comment by jonwbstr** [comment]
While working on this issue today I noticed the reply url should be http://localhost according to an important note in the article (below for reference). I had seen this before but overlooked that it was "http" and NOT "https" working now!

The doc for version 1.5 has a script for creating the application. Change line 100 and it will work for the new partner center module.

> When using the UseAuthorizationCode parameter you will be prompted to authentication interactively using the authorization code flow. The redirect URI value will generated dynamically. This generation process will attempt to find a port between 8400 and 8999 that is not in use. Once an available port has been found, the redirect URL value will be constructed (e.g. http://localhost:8400). So, it is important that you have configured the redirect URI value for your Azure Active Directory application accordingly.

**Comment by isaiahwilliams** [comment]
If anyone is still having issues please open a new issue. It appears that everyone has found a solution, so I will be closing this issue.
