### ISSUE TITLE
Validity for "-Consent" refresh token

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-docs-powershell#40]
For how long will a refresh token created using the "-Consent" switch be valid?
I can't find any information about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c68a94-87fb-43a6-023b-127f08e469c9
* Version Independent ID: 7846349e-7dfe-99cd-67e5-617493f03f0a
* Content: [New-PartnerAccessToken (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partneraccesstoken?view=partnercenterps-1.5)
* Content Source: [docs/help/New-PartnerAccessToken.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/New-PartnerAccessToken.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
Hi @o-l-a-v, 

A refresh token, regardless of how it is obtained, is only valid for 90 days. This means you will either need to re-perform the consent process every 90 days, or build a process that automatically updates it. This is possible because each time you request an access token from Azure AD a new refresh token value is returned. So, you could have a process that updates the refresh token you are using to get access tokens with a new refresh token that is obtained through the exchange.
