### ISSUE TITLE
Request documentation be updated

### ISSUE THREAD

**Issue by prysmcorp** [MicrosoftDocs/partner-center-docs-powershell#58]
Due to the breaking changes in Release 2.0 (Sep 11, 2019) could this page please be updated to reflect?

Several parameters are no longer valid, e.g. consent and resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2ecd38-7014-b642-4940-86010a7bf26a
* Version Independent ID: dca9cd31-0316-d0aa-949f-a8533c36d5cd
* Content: [Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5#feedback)
* Content Source: [docs-conceptual/partnercenterps-1.5/secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/secure-app-model.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@prysmcorp we have replaced that article with [Multi-Factor Authentication](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0) since it covers more than just the Secure Application Model. I am adding a redirect to ensure anyone attempting to access the old article will be redirected.
