### ISSUE TITLE
Migrating from 1.5 to 2.0

### ISSUE THREAD

**Issue by LukeMarlin** [MicrosoftDocs/partner-center-docs-powershell#71]
Hi,

We've used this line in production for quite some time now:
`New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com`

And now we'd like to upgrade to version 2, however with version 2, this is completely off:

- `-Consent` flag disappeared: is it now implied?
- `-Resource` disappeared. Is `-Scopes 'https://api.partnercenter.microsoft.com/user_impersonation'` an exact replacement to what we previously did?
- `Tenant` didn't exist. What should it be, our own, or the client's?

**Comment by LukeMarlin** [comment]
More precisely, I'm moving from version 1.5.1902.2.

**Comment by isaiahwilliams** [comment]
@LukeMarlin over the past several weeks we have made a number of updates to our documentation that should help. You are correct that the removal of the `Consent` parameter was done because it can be implied through the other parameter specified. Also, you are correct that the `Resource` parameter has been replaced by the `Scopes` parameter. Finally, the tenant parameter should be the tenant identifier for the Azure AD tenant where you are planning to perform an operation. If you are only performing Partner Center operations then this will be our own tenant. 

I would recommend reviewing this [document](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth) it will help with any other questions you might have.
