### ISSUE TITLE
Sharepoint PowerShell Module

### ISSUE THREAD

**Issue by rodrijp** [MicrosoftDocs/partner-center-docs-powershell#89]
Hi @isaiahwilliams,

We use  [Microsoft.Online.SharePoint.PowerShell](https://docs.microsoft.com/en-us/powershell/sharepoint/sharepoint-online/connect-sharepoint-online?view=sharepoint-ps) module to do tasks on Sharepoint. We found that [Connect-SPOService](https://docs.microsoft.com/es-es/powershell/module/sharepoint-online/connect-sposervice?view=sharepoint-ps) method only acceps a credential parameter. On the other hand, the new-PartnerAccessToken only has in the Module param the posible value "ExchangeOnline". Do you have any feedback if it's possible to use it?

Best Regards and Happy New Year!!!!
Rodrigo

**Comment by isaiahwilliams** [comment]
Hi @rodrijp, 

This is something that will need to be investigated because I am not certain you can leverage an access token with the current design of the SharePoint Online module.  Based on the documentation it appears the module only supports the password flow, which will not work for partners who have multi-factor authentication. However, before we reach any conclusions some investigating will need to be done.

**Comment by rodrijp** [comment]
Thank you @isaiahwilliams,
I appreciate your help ;-)

**Comment by isaiahwilliams** [comment]
Based on what I have learned so far, it does not appear to be an easy way to contend with this requirement. However, the good news is that we have exposed the functionality to create access tokens manually. That way if the functionality is delivered to connect to SharePoint Online PowerShell using access tokens you will have the mechanism to generate them.
