### ISSUE TITLE
Refresh Token invalidation

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/partner-center-docs-powershell#91]
The documentation mentions that the refresh token is expiring in 90 days. Are there other reasons the refresh Tokens are revoked? I have two scenarios where the behavior is unclear and I think the documentation should answer that.

- Can I use multiple refresh Token for a single app? If yes is there a limit.
- Will the Token revoked if the User giving the Consent is deactivated in the Azure AD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b50142d-5f12-052b-f0df-884b98fea713
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0)
* Content Source: [docs-conceptual/partnercenterps-2.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-2.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@StefanSchoof yes, there are four reason that aware of that will cause a refresh token to become invalid.

1. Administrator in the tenant revokes the refresh token. This can be done through a number of means but the most common is [Revoke-AzureADUserAllRefreshToken](https://docs.microsoft.com/powershell/module/azuread/revoke-azureaduserallrefreshtoken?view=azureadps-2.0) command
2. The password associated with the user account expires, once this happens all refresh tokens for this account will become invalid. Note password changes do not impact the refresh token validity
3. The refresh token expires based on the default value or due to a policy that modifies the lifetime of a token. The default lifetime is 90 days
4. The user account is disabled

There is not a limit of refresh tokens that can be used. Each time you exchange a refresh token for an access token a new refresh token will be returned as well. So, you can have a process to update the securely stored refresh token on a set interval to help avoid complications with an expired token.

**Comment by StefanSchoof** [comment]
Thanks for the quick and detailed explanation. This will help us.
