### ISSUE TITLE
ExchangeOnline Example - Module parameter cannot be found

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/partner-center-docs-powershell#93]
I'm on version partnercenter module version 3.0.4 and the command in the example returns the following error:

$token = New-PartnerAccessToken -Module ExchangeOnline
New-PartnerAccessToken : A parameter cannot be found that matches parameter name 'Module'.

I tried an alternative example found online, but it says my application is not configured correctly:
$Exchangetoken = New-PartnerAccessToken -ApplicationId &lt;ApplicationID&gt; -Scopes 'https://outlook.office365.com/.default' -Tenant &lt;PartnerTenantID&gt; -UseDeviceAuthentication

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958c342f-ff57-a57b-9426-8b1bbc9460b2
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0)
* Content Source: [docs-conceptual/partnercenterps-3.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by jonwbstr** [comment]
It would appear that after updating to 3.0.4 and rebuilding the application from scratch I'm still getting the same error. One day I will learn to just keep the working version of partnercenter module installed!

New-PartnerAccessToken : The wrong application (public or confidential) is being used with this authentication flow.
Potential issue: the redirect URI is valid, but it has been configured for the wrong app type. Check the configuration
of the app being used in the app registration portal. See https://aka.ms/msal-net-invalid-client for details.
Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or
'client_secret'.

**Comment by jonwbstr** [comment]
I contacted Partner Center support and they were able to generate a working application. Next, I created a new application using the same approach as the partner center support team, and the application in my tenant did not work, while the application in their tenant did. Definitely going to need some extra help on this error.

**Comment by jonwbstr** [comment]
Quick update. I downgraded from 3.0.4 to 3.0.3 and the token exchange started working again. I don't think 3.0.4 is supposed to be available via "update-module" just yet, considering it doesn't work as expected in my scenario.

The original issue that the example in the documentation generates an error still exists and might lead others to update to a newer version of the module and break their deployments too.

**Comment by isaiahwilliams** [comment]
@jonwbstr with respect to the AADSTS7000218 error that you were encountering that is due to the fact you are trying to utilize a confidential client (known as a web application in Azure Active Directory). When you use this type of application it requires the application identifier and the secret be specified with each authentication request. To address the error you need to create an application secret and then specify it using the Credential parameter. 

However, since you are looking to leverage the Exchange Online PowerShell module you cannot do this. You will need to leverage the following 

```powershell
New-PartnerAccessToken -Module ExchangeOnline
```

Behind the scenes that command is making request to Azure Active Directory using the application leveraged by the Exchange Online PowerShell module to get an access and refresh token. Use of this specific application is required because currently you cannot create an application Azure Active Directory that has the expected permissions.

**Comment by isaiahwilliams** [comment]
@jonwbstr quick update we have unlisted version 3.0.4 and just released version 3.0.5 which resolves both of the issues you encountered. Thank you for sharing the details with us.
